### ISSUE TITLE
Account#promote_to_merchant raises exception

### ISSUE THREAD

**Issue by akappen** [balanced/balanced-ruby#1]
Using gem version 0.2.5

I created a new buyer account and called promote_to_merchant on it.  It threw a NameError.

1.9.3p125 :052 > buyer.promote_to_merchant({
1.9.3p125 :053 >              :type => "person",
1.9.3p125 :054 >              :name => "Billy Jones",
1.9.3p125 :055 >              :street_address => "801 High St.",
1.9.3p125 :056 >              :postal_code => "94301",
1.9.3p125 :057 >              :country => "USA",
1.9.3p125 :058 >              :dob => "1969-01",
1.9.3p125 :059 >              :phone_number => "+16505551234",
1.9.3p125 :060 >            })
NameError: undefined local variable or method `merchant' for #<Balanced::Account:0x00000004a1db38>
    from .../gems/balanced-0.2.5/lib/balanced/resources.rb:67:in`promote_to_merchant'
    from (irb):52
    from.../gems/railties-3.2.3/lib/rails/commands/console.rb:47:in `start'
    from .../gems/railties-3.2.3/lib/rails/commands/console.rb:8:in`start'
    from .../gems/railties-3.2.3/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by akappen** [comment]
Sorry, here's the error with better formatting.

```
1.9.3p125 :052 > buyer.promote_to_merchant({
1.9.3p125 :053 >              :type => "person",
1.9.3p125 :054 >              :name => "Billy Jones",
1.9.3p125 :055 >              :street_address => "801 High St.",
1.9.3p125 :056 >              :postal_code => "94301",
1.9.3p125 :057 >              :country => "USA",
1.9.3p125 :058 >              :dob => "1969-01",
1.9.3p125 :059 >              :phone_number => "+16505551234",
1.9.3p125 :060 >            })
NameError: undefined local variable or method `merchant' for #<Balanced::Account:0x00000004a1db38>
    from .../gems/balanced-0.2.5/lib/balanced/resources.rb:67:in `promote_to_merchant'
    from (irb):52
    from .../gems/railties-3.2.3/lib/rails/commands/console.rb:47:in `start'
    from .../gems/railties-3.2.3/lib/rails/commands/console.rb:8:in `start'
    from.../gems/railties-3.2.3/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'

```
