### ISSUE TITLE
Cannot invalidate a bank account

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#22]
```
require 'balanced'

# create a test marketplace
api_key = Balanced::ApiKey.new.save
Balanced.configure(api_key.secret)
marketplace = Balanced::Marketplace.new.save

# underwrite seller as a merchant
merchant = Balanced::Account.new(
  :email_address => "fnietzsche@example.com",
  :name => "Friedrich Nietzche",
  :street_address => "801 High St Ste 200",
  :country_code => "USA",
  :dob => "1844-10",
  :bank_account => {
    :name => "Fred Nietzsche",
    :account_number => "204820239384",
    :bank_code => "121042882"
  }
).save

ba = merchant.bank_accounts[0]
ba.is_valid = false
ba.save()
```

Gives the following error

```
Balanced::BadRequest: Balanced::BadRequest(400)::Bad Request:: PUT https://api.balancedpayments.com/v1/marketplaces/TEST-MP2oVZxsDsvtqVWwobslJjvU/accounts/AC2r79awOqKaENWmuc6DygAh/bank_accounts/BA2rFF8vMNdgpQ5tv1OsfElH: : Invalid field "account.account" - Not a mapping Your request id is OHM50ed8f7ecf9711e19cd5026ba7e239a9. 
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/balanced-0.3.8/lib/balanced/response/balanced_exception_middleware.rb:28:in `on_complete'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/response.rb:9:in `block in call'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/response.rb:63:in `on_complete'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/response/logger.rb:20:in `call'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday_middleware-0.8.7/lib/faraday_middleware/request/encode_json.rb:21:in `call'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/connection.rb:226:in `run_request'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/faraday-0.8.1/lib/faraday/connection.rb:99:in `put'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/balanced-0.3.8/lib/balanced/client.rb:62:in `method_missing'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/balanced-0.3.8/lib/balanced.rb:68:in `method_missing'
    from /usr/local/Cellar/ruby/1.9.3-p0/lib/ruby/gems/1.9.1/gems/balanced-0.3.8/lib/balanced/resources/resource.rb:26:in `save'
    from (irb):24
    from /usr/local/bin/irb:12:in `<main>'
```

**Comment by mjallday** [comment]
Work around:

Create a new bank account with only the `uri` and `is_valid` parameters set and save that:

```
ba = merchant.bank_accounts[0]
ba2 = Balanced::BankAccount.new(:uri=>ba.uri, :is_valid=>false)
ba2.save()
```

**Comment by mahmoudimus** [comment]
This is now fixed.
