### ISSUE TITLE
Ruby 1.8.7

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#23]
Gimme that old skool flavor

```
% irb 
/Users/marshall/.rvm/gems/ruby-1.8.6-p420@global/gems/rubygems-bundler-1.0.3/lib/rubygems-    bundler/regenerate_binstubs_command.rb:48: warning: parenthesize argument(s) for future version
no such file to load -- wirble
1.8.6 :001 > require 'balanced'
Faraday: you may want to install system_timer for reliable timeouts
NoMethodError: undefined method `require_relative' for #<Object:0x10d045340>
    from /Users/marshall/.rvm/gems/ruby-1.8.6-p420/gems/balanced-0.3.8/lib/balanced/resources/resource.rb:1
    from /Users/marshall/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/marshall/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Users/marshall/.rvm/gems/ruby-1.8.6-p420/gems/balanced-0.3.8/lib/balanced/resources.rb:2
    from /Users/marshall/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Users/marshall/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Users/marshall/.rvm/gems/ruby-1.8.6-p420/gems/balanced-0.3.8/lib/balanced.rb:8
    from /Users/marshall/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Users/marshall/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from (irb):1
1.8.6 :002 > 
```

**Comment by mahmoudimus** [comment]
Since 1.8.7 is nearing end of life, this issue is not relevant.
